"""pet-agent 领域契约层。

所有跨边界的数据结构都在此定义：API 请求/响应、节点间传递、持久化实体、
planner 的子任务与计划。各层不得自定义与之重复的结构体。
"""

from app.schemas.behavior import (
    AcousticFeatures,
    BehaviorAction,
    BehaviorInterpretation,
    CaseMatch,
    ContextLabel,
    EvidenceItem,
    EvidenceKind,
    EvidenceMode,
    FeatureQuality,
    IndividualizationProfile,
    IntentCandidate,
    MeowRecord,
    PendingInterpretation,
    action_label,
)
from app.schemas.digest import (
    QUOTE_MIN_CHARS,
    DailySummary,
    DigestCandidate,
    DigestMessage,
    DigestStats,
    ExtractionSource,
    RejectedCandidate,
)
from app.schemas.guard import GuardResult, Severity, Violation, ViolationType
from app.schemas.health import (
    FORBIDDEN_PHRASES,
    MIN_COVERAGE_FOR_ASSESSMENT,
    HealthAssessment,
    HealthDataPolicy,
    HealthRecord,
    HealthRecordSource,
    RedFlagHit,
    SignalDeviation,
    UrgencyLevel,
)
from app.schemas.input import (
    FAST_PATH_INTENTS,
    INTENT_POLICIES,
    MISROUTE_COSTS,
    AudioKind,
    InputIntent,
    IntentPolicy,
    MemoryWritePermission,
    MisrouteCost,
    RawInput,
    RouteSlots,
    SessionContext,
    misroute_cost,
    policy_for,
)
from app.schemas.memory import (
    SUBJECT_FALLBACK_PREFIX,
    ASR_CONFIDENCE_DISCOUNT,
    EVENT_HALFLIFE_DAYS,
    LAYER_ACCESS_MODE,
    SOURCE_TRUST,
    ContextInjectionBlock,
    ConversationTurn,
    EventType,
    MemoryAccessMode,
    MemoryEvent,
    MemoryItem,
    MemoryLayer,
    MemorySource,
    MemoryStatus,
    MemoryWriteDecision,
    Polarity,
    RetrievalSource,
    ScoreBreakdown,
    WriteAction,
)
from app.schemas.observation import (
    FORBIDDEN_INFERENCE_PHRASES,
    SCENE_OBJECTS,
    MediaKind,
    ModelObservation,
    find_forbidden_inference,
)
from app.schemas.pet import (
    PetProfile,
    PetProfileDraft,
    Species,
    Trait,
    TraitLayer,
    VisualProfile,
)
from app.schemas.plan import (
    Dependency,
    DependencyKind,
    Plan,
    PlanResult,
    PriorAdjustment,
    PriorOperation,
    PriorSkip,
    PriorTargetField,
    SubTask,
    SubTaskKind,
    SubTaskResult,
    SubTaskStatus,
)
from app.schemas.session import SessionMessage
from app.schemas.story import (
    DISCLAIMER_ENTERTAINMENT,
    ENTERTAINABLE_EVENT_TYPES,
    ENTERTAINABLE_SOURCES,
    HEALTH_NOTICE,
    PHYSIOLOGY_WORDS,
    DailyStory,
    ExcludedBeat,
    InfoLayer,
    StoryBeat,
    StoryTimeOfDay,
    StoryTone,
    find_physiology_words,
    layer_display,
    time_display,
)
from app.schemas.trace import ErrorKind, ErrorSeverity, NodeError, NodeTrace

__all__ = [
    # ── pet ──
    "PetProfile",
    "PetProfileDraft",
    "VisualProfile",
    "Trait",
    "TraitLayer",
    "Species",
    # ── memory ──
    "MemoryEvent",
    "MemoryItem",
    "MemoryLayer",
    "MemoryAccessMode",
    "MemoryStatus",
    "MemorySource",
    "MemoryWriteDecision",
    "EventType",
    "Polarity",
    "RetrievalSource",
    "ScoreBreakdown",
    "WriteAction",
    "ContextInjectionBlock",
    "ConversationTurn",
    "LAYER_ACCESS_MODE",
    "SOURCE_TRUST",
    "EVENT_HALFLIFE_DAYS",
    "ASR_CONFIDENCE_DISCOUNT",
    # ── behavior ──
    "BehaviorInterpretation",
    "AcousticFeatures",
    "ContextLabel",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceMode",
    "FeatureQuality",
    "IntentCandidate",
    "IndividualizationProfile",
    # ── input / routing ──
    "RawInput",
    "AudioKind",
    "InputIntent",
    "RouteSlots",
    "SessionContext",
    "IntentPolicy",
    "MemoryWritePermission",
    "MisrouteCost",
    "FAST_PATH_INTENTS",
    "INTENT_POLICIES",
    "MISROUTE_COSTS",
    "SUBJECT_FALLBACK_PREFIX",
    "misroute_cost",
    "policy_for",
    # ── guard ──
    "GuardResult",
    "Violation",
    "ViolationType",
    "Severity",
    # ── health ──
    "HealthAssessment",
    "HealthRecord",
    "HealthRecordSource",
    "HealthDataPolicy",
    "RedFlagHit",
    "SignalDeviation",
    "UrgencyLevel",
    "FORBIDDEN_PHRASES",
    "MIN_COVERAGE_FOR_ASSESSMENT",
    # ── plan ──
    "Plan",
    "PlanResult",
    "SubTask",
    "SubTaskKind",
    "SubTaskResult",
    "SubTaskStatus",
    "Dependency",
    "DependencyKind",
    "PriorAdjustment",
    "PriorOperation",
    "PriorSkip",
    "PriorTargetField",
    # ── trace ──
    "NodeError",
    "NodeTrace",
    "ErrorKind",
    "ErrorSeverity",
    # ── behavior（四层信息分层的动作层）──
    "BehaviorAction",
    "CaseMatch",
    "MeowRecord",
    "PendingInterpretation",
    "action_label",
    # ── digest（每日总结）──
    "DailySummary",
    "DigestCandidate",
    "DigestMessage",
    "DigestStats",
    "ExtractionSource",
    "RejectedCandidate",
    "QUOTE_MIN_CHARS",
    # ── observation（多模态事实）──
    "ModelObservation",
    "MediaKind",
    "SCENE_OBJECTS",
    "FORBIDDEN_INFERENCE_PHRASES",
    "find_forbidden_inference",
    # ── session（会话消息）──
    "SessionMessage",
    # ── story（宠物的一天）──
    "DailyStory",
    "StoryBeat",
    "StoryTone",
    "StoryTimeOfDay",
    "InfoLayer",
    "ExcludedBeat",
    "PHYSIOLOGY_WORDS",
    "DISCLAIMER_ENTERTAINMENT",
    "HEALTH_NOTICE",
    "ENTERTAINABLE_EVENT_TYPES",
    "ENTERTAINABLE_SOURCES",
    "find_physiology_words",
    "time_display",
    "layer_display",
]
